version: "3.9"

volumes:
  postgres-db:
  postgres-admin:

services:
  php-fpm:
    build:
      context: .
      dockerfile: ./config/php-fpm/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
        - XDEBUG_PORT=${XDEBUG_PORT}
        - USER_ID=${USER_ID}
    ports:
      - 9000:9000
    volumes:
      - ./symfony-app:/var/www/html/backend/
      - ./logs/php-fpm:/tmp/
      - ./config/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    container_name: php-fpm
    restart: "no"
    depends_on:
      - postgres-db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres-db:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=app
    container_name: postgres-db
    restart: "no"

  postgres-admin:
    image: dpage/pgadmin4:snapshot
    ports:
      - "5050:80"
    volumes:
      - postgres-admin/:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    container_name: postgres-admin
    depends_on:
      - postgres-db
    restart: "no"

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./symfony-app/:/var/www/html/backend/
      - ./vue-app/dist/:/var/www/html/frontend/
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx/:/var/log/nginx
    depends_on:
      - php-fpm

  vue-app:
    build:
      context: .
      dockerfile: ./config/vue/Dockerfile
      args:
        - USER_ID=${USER_ID}
    network_mode: host
    volumes:
      - ./vue-app/:/var/www/html/frontend/
    container_name: vue-app
    restart: "no"
    command: sh -c "npm install; npm run dev"
    depends_on:
      - nginx
